config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups do
    resources :comments
  end

  get 'index', to: 'welcome#index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                    length: { minimum: 3 }
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!


  def create
		@group = Group.find(params[:group_id])
		@comment = @group.comments.create(comment_params)


		redirect_to group_path(@group)
	end

	def destroy
		@group = Group.find(params[:group_id])
		@comment = @group.comments.find(params[:id])
		@comment.destroy

		redirect_to group_path(@group)
	end

  private
    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @groups = Group.all

  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:title, :description, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
		<div class="comment_photo">
			<% if comment.name="yumin" %>
				<%= image_tag "pic1.png" %>
			<% end %>
		</div>
		<div class="comment_content">
			<span class="comment_name"><strong><%= comment.name %></strong></span>
			<p class="comment_body"><%= simple_format(comment.body) %></p>
			<p style="color:#c6c6c6" class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago
				<% if current_user && current_user.admin? %>
				<span><%= link_to 'Delete', [comment.group, comment],
											  method: :delete,
											  class: "button",
											 	data: { confirm: 'Are you sure?' } %></span>
			 	<% end %>
			</p>
		</div>

</div>

app/views/comments/_form.html.erb
<%= form_for([@group, @group.comments.build]) do |f| %>
<form class="form-inline">
	<div class="form-group">
		<%= f.text_area :body, class: "form-control commet-submit", placeholder: "Please click the icon at the top right corner and contact me" %>
		<span id="contact">
			<a href="mailto:yumin3991@gmail.com?Subject=Hello%20again" target="_top">Submit</a>
		</span>
	</div>
</form>
<% end %>

app/views/groups/_form.html.erb
<%= form_for :group, url: groups_path do |f| %>

  <% if @group.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@group.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', groups_path %>

app/views/groups/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/groups/index.html.erb
<div class="welcome"></div>

app/views/groups/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<div class="main-content">
  <div class="panel_1">
    <h3><%= @group.title %></h3>
    <h1><%= @group.description %></h1>

  </div>
  <hr>
    <div class="panel_2">
  		<%= render @group.comments %>
    </div>
    <div class="panel_3">
  		<%= render "comments/form" %>
    </div>
</div>

app/views/layouts/_feature.html.erb
<div class="feature">
  <div id="flip">個人簡歷/聯絡方式
    <p><i class="fa fa-angle-down" aria-hidden="true"></i></p>
  </div>
    <div id="panel">
    <p>2012.9-2016.6&nbsp;台灣師範大學-設計學系</p>
    <p>2016.6-2016.9&nbsp;LingQ新創公司-行銷實習</p>
    <p>2013.1-2016.4&nbsp;台灣師範大學-行政工讀</p>
    <p>2013.2-2014.1&nbsp;台北數位藝術中心-藝術志工</p>
    <hr>
    <p>email：yumin3991@gmail.com</p>
    <p>github：https://github.com/emily0</p>
    <p>phone：0910439109</p>
  </div>
  <div id="flip">程式語言/軟體技能</div>
    <div id="panel-skills">
      <div class="container">
      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="80"
        aria-valuemin="0" aria-valuemax="100" style="width:80%">
          HTML/CSS
        </div>
      </div>
      </div>

      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="35"
        aria-valuemin="0" aria-valuemax="100" style="width:35%">
          JS/jQuery
        </div>
      </div>
      </div>

      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="50"
        aria-valuemin="0" aria-valuemax="100" style="width:50%">
          Ruby on Rails
        </div>
      </div>
      </div>

      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="70"
        aria-valuemin="0" aria-valuemax="100" style="width:70%">
          MVC framwork
        </div>
      </div>
      </div>

      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar progress-bar2" role="progressbar" aria-valuenow="100"
        aria-valuemin="0" aria-valuemax="100" style="width:100%">
          Illustrator
        </div>
      </div>
      </div>

      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar progress-bar2" role="progressbar" aria-valuenow="95"
        aria-valuemin="0" aria-valuemax="100" style="width:95%">
          Photoshop
        </div>
      </div>
      </div>

      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar progress-bar2" role="progressbar" aria-valuenow="80"
        aria-valuemin="0" aria-valuemax="100" style="width:80%">
          After Effect
        </div>
      </div>
      </div>

      <div class="col-sm-8">
      <div class="progress">
        <div class="progress-bar progress-bar2" role="progressbar" aria-valuenow="90"
        aria-valuemin="0" aria-valuemax="100" style="width:90%">
          Premiere
        </div>
      </div>
      </div>
    </div>
    </div>
    <div class="test">個人特質
      <div class="container">
        <div class="floating-box"><h4><span class="label label-default">independent</span></h4></div>
        <div class="floating-box"><h4><span class="label label-default">genuine</span></h4></div>
        <div class="floating-box"><h4><span class="label label-default">confident</span></h4></div>
        <div class="floating-box"><h4><span class="label label-default">optimistic</span></h4></div>
        <div class="floating-box"><h4><span class="label label-default">practical</span></h4></div>
        <div class="floating-box"><h4><span class="label label-default">punctual</span></h4></div>
        <div class="floating-box"><h4><span class="label label-default">unique</span></h4></div>
        <div class="floating-box"><h4><span class="label label-default">energetic</span></h4></div>
      </div>
    <div>
</div>

<script>
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
});
</script>

app/views/layouts/_header.html.erb
<h3>THis is header</h3>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="logo"><%= image_tag "Pickone.png" %></div>
  <div class="site-nav">
    <ul class="menu">
      <li>群組</li>
      <li>#Pickone</li>
      <li>#社群行銷</li>
      <li>#程式除錯</li>
      <li>#場地問題</li>
      <li class="item">#找人才&nbsp;<span class="badge">8</span></li>
      <li>#會議討論</li>
      <li>#隨便聊</li>
    </ul>

    <ul class="menu">
      <li>成員</li>
      <li><i class="fa fa-user" aria-hidden="true"></i>&nbsp;Picker</li>
      <li><i class="fa fa-user" aria-hidden="true"></i>&nbsp;黃鈺閔</li>
    </ul>
  </div>
  <div class="site-meta">
    <div id="profile">
      <%= image_tag "profile.png" %>
    </div>
    <div class="name">
      <span>黃鈺閔</span>
      <p><i class="fa fa-circle" aria-hidden="true"></i>&nbsp;online</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resume</title>
    <%= csrf_meta_tags %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="wrapper">
      <div id="header"><%= render 'layouts/header' %></header>
      <%= render 'layouts/sidebar' %>
      <div id="main">
        <%= yield %>
        <% if !current_page?(root_path) && !current_page?(groups_path) %>
          <%= render 'layouts/feature' %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/index.html.erb
<div class="container">
  <% @groups.each do |group| %>
    <%= group.title %>
  <% end %>
<%= link_to 'New group', new_group_path %>
</div>

app/views/welcome/index.html.erb
<div class="welcome"></div>